### ISSUE TITLE
Self consistency checks (zh vs zdr, etc)

### ISSUE THREAD

**Issue by kenkehoe** [ARM-Development/RadTraQ#16]
radar_plot_scatter.pro

**Comment by AdamTheisen** [comment]
![image](https://user-images.githubusercontent.com/13421074/134209154-897ce6d5-91c4-4dcd-bb73-20de5a1595ad.png)

**Comment by kenkehoe** [comment]
@AdamTheisen  Scott mentioned using histograms as well (or instead). Do you understand what he was suggesting?

**Comment by AdamTheisen** [comment]
Yeah, just a 2D histogram/heatmap like this: https://www.python-graph-gallery.com/83-basic-2d-histograms-with-matplotlib
