### ISSUE TITLE
Consider adding pre-commit configuration

### ISSUE THREAD

**Issue by djhoese** [ARM-Development/RadTraQ#37]
Adam mentioned wanting to gather new contributors for this project and one thing that can happen when bringing in a lot of new people is differences in coding style or ability. It may be of interesting to the maintainers of this project to consider using pre-commit to encourage consistent code style and quality:

https://pre-commit.com/

These configs can definitely get crazy, but I feel that in the end they benefit projects more than the time they take to setup. You can even enable pre-commit.ci to automatically run checks for pull requests:

https://pre-commit.ci/

You can find examples in the various examples on the above sites, but I find it useful to look at other projects using pre-commit:

 * https://github.com/pytroll/satpy/blob/main/.pre-commit-config.yaml
 * https://github.com/dask/dask/blob/main/.pre-commit-config.yaml
 * https://github.com/pydata/xarray/blob/main/.pre-commit-config.yaml

Just an idea. Feel free to close this.

**Comment by mgrover1** [comment]
I like the idea of using pre-commit here! We use in one of the other ARM-related repos (ACT) https://github.com/ARM-DOE/ACT, and it would be good to include here too!

**Comment by kenkehoe** [comment]
I like this idea, but understand 0%. Maybe we can have an ACT call to show this off?

**Comment by mgrover1** [comment]
Sure! At today's meeting?

**Comment by AdamTheisen** [comment]
Let's try and revisit this at the next ACT call
