### ISSUE TITLE
matplotlib < 3.5 requirement?

### ISSUE THREAD

**Issue by akrherz** [ARM-Development/RadTraQ#39]
We'd (Iowa State) like to use this package, but the matplotlib < 3.5 pin is a bit problematic.  I couldn't find an issue here documenting the issues with that or 3.6 matplotlib?

**Comment by AdamTheisen** [comment]
@akrherz Very happy to see there's interest!  I will take a look today and get everything updated and released if I can.  More soon!

**Comment by AdamTheisen** [comment]
@akrherz I went through and updated the requirements and made sure the plotting still works with the latest matplotlib, added in some more robust testing, and did another release.  Let me know if there are any other issues you see or requests you would like to see.  As I mentioned in an open science workshop earlier this year, we definitely are looking for users and contributors to this code as anything that's added could directly benefit the ARM program as well.  Looking forward to hearing from you!

**Comment by akrherz** [comment]
Thank you @AdamTheisen ! Will requirement [act-atmos](https://github.com/conda-forge/act-atmos-feedstock/blob/main/recipe/meta.yaml#L26) get updated as well?

**Comment by AdamTheisen** [comment]
@akrherz act-atmos should not be pinned on a matplotlib version but want to pull in @mgrover1  and @zssherman to confirm

**Comment by zssherman** [comment]
@AdamTheisen So we do not pin it in our CI, but we do pin it on conda-forge, so if installing on conda-forge it will pin for <3.5 matplotlib-base. I believe this was due to an issue with cartopy originally. I can try to do a bump build release with just that change and see if it passes.

**Comment by AdamTheisen** [comment]
@zssherman let's give it a try and see

**Comment by zssherman** [comment]
@AdamTheisen @akrherz Looks like the tests ran with the matplotlib pin removed, I merged the PR, say give it 10-15 mins for conda forge downloads to update.

**Comment by AdamTheisen** [comment]
Closing this back out but let us know if you have any other questions or issues to bring up!

**Comment by akrherz** [comment]
Perfect, conda installed `act-atmos` and pip installed `radtraq` without going into dependency hell with my heavy env.
